name: build apk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: build android app
        run: ./gradlew assembleRelease
      - name: sign android app
        id: sign-android-app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: upload artifact
        uses: actions/upload-artifact@v2 
        with: 
          name: 'app-release' 
          path: ${{ steps.sign-app.outputs.signedReleaseFile }}
